name: Terraform Plan

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'terraform/**'
      
permissions:
  pull-requests: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        id: terraform_plan # Corrected ID here
        run: |
          plan_output=$(terraform init)
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          echo "$plan_output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Step 2: Comment on Pull Request using the output from the previous step
      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const planOutput = `${{ steps.terraform_plan.outputs.plan_output }}` || 'Terraform Plan Failed or no changes detected';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `Terraform Plan:\n\n\`\`\`\n${planOutput}\n\`\`\``
            });
